
# 📊 Complete NumPy Tutorial: From Basics to Advanced

This notebook covers everything you need to learn **NumPy** for **data analysis, machine learning, deep learning, and AI**.

By the end of this notebook, you will know how to:
- Work with arrays
- Perform vectorized operations
- Use advanced indexing and broadcasting
- Perform linear algebra operations
- Integrate NumPy with ML/DL workflows



## 1️⃣ Introduction to NumPy

NumPy (Numerical Python) is a fundamental library for numerical computing in Python. It provides:
- **ndarray**: fast, multi-dimensional array
- **Vectorized operations**: fast computations
- **Broadcasting**: operations on arrays of different shapes
- **Linear algebra, random, statistics, and more**


In [10]:
# Importing NumPy
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.0.2


## 2️⃣ Creating NumPy Arrays

NumPy arrays can be created from Python lists or tuples.

In [11]:
import ipykernel
print(ipykernel.__version__)

6.31.0


In [12]:
# Array from list
arr = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr)
print("Type:", type(arr))
print("Shape:", arr.shape)


1D Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)


In [13]:
# Cell 6: Multi-dimensional array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2d)
print("Shape:", arr2d.shape)
print("N-Dimension",arr2d.ndim)


2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
N-Dimension 2


### Common Array Creation Functions
- `np.zeros(shape)` → array of zeros
- `np.ones(shape)` → array of ones
- `np.arange(start, stop, step)` → like Python range
- `np.linspace(start, stop, num)` → evenly spaced numbers
- `np.eye(n)` → identity matrix

In [14]:
# Examples
zeros = np.zeros((2,3))
ones = np.ones((3,2))
range_arr = np.arange(0, 10, 2)
linspace_arr = np.linspace(0, 1, 5)
eye = np.eye(3)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Range:", range_arr)
print("Linspace:", linspace_arr)
print("Identity:\n", eye)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 3️⃣ Array Attributes

Useful attributes:
- `shape` → dimensions
- `ndim` → number of axes
- `size` → total elements
- `dtype` → data type
- `itemsize` → size of each element in bytes
- `nbytes` → total bytes consumed

In [16]:
# Attribute Examples
arr = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)
print("Item size:", arr.itemsize)
print("Total bytes:", arr.nbytes)


Array:
 [[1. 2. 3.]
 [4. 5. 6.]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: float64
Item size: 8
Total bytes: 48


## 4️⃣ Indexing and Slicing

NumPy arrays can be indexed and sliced like Python lists:

In [17]:
# Basic Indexing
arr = np.array([10,20,30,40,50])
print("Original:", arr)
print("Index 0:", arr[0])
print("Last element:", arr[-1])
print("Slice 1:4:", arr[1:4])


Original: [10 20 30 40 50]
Index 0: 10
Last element: 50
Slice 1:4: [20 30 40]


In [18]:
# 2D Array Indexing
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original 2D array:\n", arr2d)
print("Element [1,2]:", arr2d[1,2])
print("Row 0:", arr2d[0])
print("Column 1:", arr2d[:,1])
print("Subarray:\n", arr2d[0:2, 1:3])


Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element [1,2]: 6
Row 0: [1 2 3]
Column 1: [2 5 8]
Subarray:
 [[2 3]
 [5 6]]


In [19]:
# Boolean Indexing
"""
### Boolean Indexing
Select elements based on condition
"""
arr = np.array([1,2,3,4,5,6])
print("Original:", arr)
print("Elements > 3:", arr[arr>3])


Original: [1 2 3 4 5 6]
Elements > 3: [4 5 6]


## 5️⃣ Array Operations

NumPy supports **element-wise operations**:
- Arithmetic: `+ - * / % **`
- Comparisons: `> < == !=`
- Universal functions (ufunc): `np.sqrt`, `np.exp`, `np.log`

In [20]:
# Examples
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a + b =", a+b)
print("a * b =", a*b)
print("a ** 2 =", a**2)
print("sqrt(a) =", np.sqrt(a))
print("exp(a) =", np.exp(a))
print("log(a+1) =", np.log(a+1))


a + b = [5 7 9]
a * b = [ 4 10 18]
a ** 2 = [1 4 9]
sqrt(a) = [1.         1.41421356 1.73205081]
exp(a) = [ 2.71828183  7.3890561  20.08553692]
log(a+1) = [0.69314718 1.09861229 1.38629436]


### Aggregation Functions
- `np.sum`, `np.mean`, `np.min`, `np.max`, `np.std`, `np.var`, `np.cumsum`, `np.cumprod`

In [21]:
# Examples
arr = np.array([[1,2,3],[4,5,6]])
print("Sum:", np.sum(arr))
print("Sum axis=0:", np.sum(arr, axis=0))
print("Sum axis=1:", np.sum(arr, axis=1))
print("Mean:", np.mean(arr))
print("Cumulative sum:", np.cumsum(arr))


Sum: 21
Sum axis=0: [5 7 9]
Sum axis=1: [ 6 15]
Mean: 3.5
Cumulative sum: [ 1  3  6 10 15 21]


## 6️⃣ Reshaping Arrays
- `reshape()`
- `flatten()`
- `ravel()`
- `transpose()`

In [22]:
# Examples
arr = np.arange(12)
print("Original:", arr)
reshaped = arr.reshape((3,4))
print("Reshaped (3x4):\n", reshaped)
print("Flattened:", reshaped.flatten())
print("Raveled:", reshaped.ravel())
print("Transposed:\n", reshaped.T)


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## 7️⃣ Stacking and Splitting
- `np.vstack`, `np.hstack`, `np.concatenate`
- `np.split`, `np.hsplit`, `np.vsplit`

In [23]:
# Examples
a = np.array([1,2,3])
b = np.array([4,5,6])
vstacked = np.vstack((a,b))
hstacked = np.hstack((a,b))
print("Vstack:\n", vstacked)
print("Hstack:", hstacked)


Vstack:
 [[1 2 3]
 [4 5 6]]
Hstack: [1 2 3 4 5 6]


## 8️⃣ Broadcasting
- Operations between arrays of different shapes

In [24]:
# Example
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])
print("Original a:\n", a)
print("Broadcast a + b:\n", a + b)


Original a:
 [[1 2 3]
 [4 5 6]]
Broadcast a + b:
 [[2 4 6]
 [5 7 9]]


## 9️⃣ Linear Algebra
- `np.dot`, `np.matmul`, `np.linalg.inv`, `np.linalg.det`, `np.linalg.eig`

In [25]:
# Example
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("A dot B:\n", np.dot(A,B))
print("Determinant of A:", np.linalg.det(A))
print("Inverse of A:\n", np.linalg.inv(A))


A dot B:
 [[19 22]
 [43 50]]
Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## 🔟 Random Module
- `np.random.rand`, `np.random.randn`, `np.random.randint`, `np.random.choice`, `np.random.seed`

In [26]:
# Examples
np.random.seed(42)
print("Random uniform 3x3:\n", np.random.rand(3,3))
print("Random normal 3x3:\n", np.random.randn(3,3))
print("Random integers 0-10:", np.random.randint(0,10,5))


Random uniform 3x3:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Random normal 3x3:
 [[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606]]
Random integers 0-10: [2 6 3 8 2]


## ✅ Summary

In this notebook, we learned:
- Array creation and attributes
- Indexing, slicing, boolean indexing
- Vectorized operations, aggregation, and broadcasting
- Linear algebra operations
- Random numbers

Next steps:
- Apply NumPy in **data analysis** with Pandas
- Use NumPy arrays in **ML/DL frameworks**
- Practice **advanced indexing and performance optimization**